# Generated by Django 2.2 on 2021-11-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(default='', max_length=200)),
                ('bookAuthor', models.CharField(default='', max_length=200)),
                ('bookCategory', models.CharField(default='', max_length=200)),
                ('bookDescription', models.CharField(default='', max_length=2000)),
                ('bookRating', models.FloatField(default=0)),
                ('bookImage', models.ImageField(default='images/none/noimg.jpg', upload_to='images')),
            ],
        ),
    ]
