# Generated by Django 2.2 on 2021-11-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='bookImage',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='books/images'),
        ),
    ]
