# Generated by Django 2.2 on 2021-11-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20211108_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='bookImage',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images'),
        ),
    ]
